spring.application.name=configuration
Group Data Exchange Framework is an overall framework for exchange of data between NYL. There types of exchanges that can happen:
are P
1. Partners (Client or TPAs) sending data into NYL
2. NYL sending data to Partners (Clients/TPAs/Downstream systems like FINEOS/MUP/REED etc.)
This framework provides a configurable solution to both of the above exchange types.
It consists of the below components:
1. Configuration Console
2.Batch Application
3. Rules Processor (Validations/Transformations)
4. Audit and Error Handling
5.Dashboards
